apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    role: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      role: nodejs
  template:
    metadata:
      labels:
        role: nodejs
    spec:
      containers:
        - name: nodedeploy-container
          image: mprambadi/docker-nodejs
          ports:
            - containerPort: 3000